AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable
  Include:
    - "Casks/**/*.rb"
    - "Formula/**/*.rb"
  Exclude:
    - "vendor/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  Exclude:
    - "Casks/**/*.rb"
    - "Formula/**/*.rb"

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 200

Layout/HashAlignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
